import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { MARKDOWN_PATH } from "@/lib/site-data";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("scroll-smooth font-sans", inter.variable)}>
      <head>
        {/* Lets agents find the markdown rendering of this site without executing JS. */}
        <link rel="alternate" type="text/markdown" href={MARKDOWN_PATH} />
      </head>
      <body>{children}</body>
    </html>
  );
}
